import json
import pandas as pd
from typing import Dict, Any, Optional
from pathlib import Path
import config
from modules import database

def export_entities_csv(output_path: Optional[Path] = None, db_path: Optional[Path] = None) -> str:
    """Exports entities to CSV format."""
    df = database.get_entities_df(db_path=db_path)
    # Ensure required columns
    export_df = df[["entity_type", "entity_name", "page", "evidence"]].copy() if not df.empty else pd.DataFrame(columns=["entity_type", "entity_name", "page", "evidence"])
    
    path = output_path or (config.EXPORTS_DIR / "entities.csv")
    export_df.to_csv(path, index=False, encoding="utf-8")
    return export_df.to_csv(index=False)


def export_dependencies_csv(output_path: Optional[Path] = None, db_path: Optional[Path] = None) -> str:
    """Exports dependencies to CSV format."""
    df = database.get_dependencies_df(db_path=db_path)
    export_df = df[["source", "relationship", "target", "page", "evidence"]].copy() if not df.empty else pd.DataFrame(columns=["source", "relationship", "target", "page", "evidence"])
    
    path = output_path or (config.EXPORTS_DIR / "dependencies.csv")
    export_df.to_csv(path, index=False, encoding="utf-8")
    return export_df.to_csv(index=False)


def export_issues_csv(output_path: Optional[Path] = None, db_path: Optional[Path] = None) -> str:
    """Exports issues/inconsistencies to CSV format."""
    df = database.get_issues_df(db_path=db_path)
    export_df = df[["issue_type", "entity", "description", "page", "status"]].copy() if not df.empty else pd.DataFrame(columns=["issue_type", "entity", "description", "page", "status"])
    
    path = output_path or (config.EXPORTS_DIR / "issues.csv")
    export_df.to_csv(path, index=False, encoding="utf-8")
    return export_df.to_csv(index=False)


def export_analysis_report_json(output_path: Optional[Path] = None, db_path: Optional[Path] = None) -> str:
    """Exports full analysis report as a structured JSON."""
    metrics = database.get_dashboard_metrics(db_path=db_path)
    docs = database.get_documents_list(db_path=db_path)
    entities_df = database.get_entities_df(db_path=db_path)
    deps_df = database.get_dependencies_df(db_path=db_path)
    issues_df = database.get_issues_df(db_path=db_path)

    report: Dict[str, Any] = {
        "report_title": "AUTOSAR HLD Architecture Analysis Report",
        "disclaimer": "This report is generated by an AI-assisted analysis tool. All potential issues require review and confirmation by an authorized systems/software engineer.",
        "summary_metrics": metrics,
        "documents": docs,
        "entities": entities_df.to_dict(orient="records") if not entities_df.empty else [],
        "dependencies": deps_df.to_dict(orient="records") if not deps_df.empty else [],
        "potential_issues": issues_df.to_dict(orient="records") if not issues_df.empty else []
    }

    path = output_path or (config.EXPORTS_DIR / "analysis_report.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    return json.dumps(report, indent=2, ensure_ascii=False)
